name: Build veh_patch_smart DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build DLL
        run: cmake --build build --config Release

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: veh_patch_smart
          path: build/Release/*.dll
